 //PERMISSION
module.exports = {
    //STUDENT MODULE
    STUDENT: {
        PROCESS_CSV: "PROCESS_CSV",
        SAVE_CSV: "SAVE_CSV",
        STUDENT_LIST: "STUDENT_LIST",
        STUDENT_BY_ID: "STUDENT_BY_ID",
        PROFILE_UPDATE: "PROFILE_UPDATE",
        CREATE_STUDENT: "CREATE_STUDENT",
        UPDATE_STUDENT: "UPDATE_STUDENT",
        DELETE: "DELETE",
        EXPORT_LIST: "EXPORT_LIST",
    },
    //LOG MODULE
    LOG: {
        GET_LOGIN_LOG: "GET_LOGIN_LOG",
        GET_SYSTEM_LOG: "GET_SYSTEM_LOG",
    },
    //ATTENDANCE MODULE
    ATTENDANCE: {
        PRESENT: "PRESENT",
        GET_TODAY_ATTENDANCE: "GET_TODAY_ATTENDANCE",
        GET_STUDENT_YEARLY_STATS: "GET_STUDENT_YEARLY_STATS",
        GET_PRESENT_HISTORY: "GET_PRESENT_HISTORY",
    },
    
}
